# ::: MLB STATS API {https://statsapi.mlb.com/api/v1/<endpoint>?<query_params>}
# get all MLB teams example → https://statsapi.mlb.com/api/v1/teams?sportId=1
GET https://statsapi.mlb.com/api/v1/teams?sportId=1

###

# ::: 
Get https://statsapi.mlb.com/api/v1/schedule?sportId=1&teamId=144&season=2023&gameType=R

###

# ::: 
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2023&gameType=R