import { Open_Sans } from "next/font/google";
import "./globals.css";

const font = Open_Sans({
  subsets: ["latin"],
  variable: "--font-general",
  preload: true,
});

export const metadata = {
  title: "My MLB HQ",
  description: "Generated by Joshua Wilde Hawk using create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
