import './globals.css'
import { Inter, Open_Sans, Rubik } from 'next/font/google'

// Components
import Navbar from './components/Navbar'

const font = Open_Sans({
	subsets: ['latin'],
	variable: '--font-general',
	preload: true,
})

export const metadata = {
	title: 'My MLB HQ',
	description: 'Generated by Joshua Wilde Hawk using create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={font.className}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
